version: 2

jobs:
  # Build & Deploy against development backend
  "build-dev":
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: apk add --no-cache bash

      # Restoration of node_modules from cache.
      - restore_cache:
          key: docker-tc-notify-{{ checksum "package-lock.json" }}

      # Build of Docker image.
      - run:
          name: Build of Docker image
          command: ./build.sh development

      # Caching node modules.
      - save_cache:
          key: docker-tc-notify-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only: dev-circleci
